title: "utk's space"
email: officialuser.utk@gmail.com
description: "I write about AI stuff."
twitter_username: UttsPutts
github_username: utkarsh-ankit
minimal_mistakes_skin: dirt #neon
search: true

# ─── Build settings ────────────────────────────────────────────────
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"

# ─── Plugins ───────────────────────────────────────────────────────
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# ─── Author ────────────────────────────────────────────────────────
author:
  name: "Utkarsh Ankit"
  avatar: "/assets/images/awc.jpg"
  bio: "I write about AI stuff."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/utkarsh-ankit/"
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/UttsPutts"
    - label: "LeetCode"
      icon: "fas fa-fw fa-code"
      url: "https://leetcode.com/u/utk_ink/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/utkarsh-ankit"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://utkarsh-ankit.medium.com/"

# ─── Defaults ──────────────────────────────────────────────────────
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false      # hides “n min read”
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# ─── Archives ──────────────────────────────────────────────────────
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# ─── Collections ───────────────────────────────────────────────────
collections:
  publications:
    output: true
    permalink: "/:collection/:path/"

# ─── Site-wide toggles ─────────────────────────────────────────────
back_to_top: false          # removes “BACK TO TOP ↑”
back_to_top_text: ""
