title: "utk's space"
email: officialuser.utk@gmail.com
description: "I write about AI stuff."
twitter_username: UttsPutts #https://x.com/UttsPutts
github_username: utkarsh-ankit #https://github.com/utkarsh-ankit
minimal_mistakes_skin: dirt #neon
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.1
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

# Note: The following author links are displayed in the sidebar
author:
  name: "Utkarsh Ankit"
  avatar: "/assets/images/bio-photo.jpg" # Optional: path to your profile picture
  bio: "I write about AI stuff."
  links:
    - label: "LinkedIn"                 # <-- NEW LINKEDIN ENTRY
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/utkarsh-ankit/" # <-- CHANGE THIS URL
      
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"   # <-- THIS IS THE CORRECTED X ICON
      url: "https://x.com/UttsPutts"

    - label: "LeetCode"
      icon: "fas fa-fw fa-code"
      url: "https://leetcode.com/u/utk_ink/"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/utkarsh-ankit"

    - label: "Medium"                   # <-- NEW MEDIUM ENTRY
      icon: "fab fa-fw fa-medium"
      url: "https://utkarsh-ankit.medium.com/" # <-- CHANGE THIS URL

footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://x.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
  show_rss: false  # <-- ADD THIS LINE

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/
